import { CapgeminiQuestion } from "./types";

export const CPP_QUESTIONS: CapgeminiQuestion[] = [
  {
    id: "capg-cpp-01",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "Polymorphism & Virtual Functions",
    difficulty: "Medium",
    type: "output-prediction",
    title: "Virtual Method Dispatch vs Early Binding",
    question: "Predict the output of the following C++ program:",
    language: "cpp",
    codeSnippet: `#include <iostream>
using namespace std;

class Base {
public:
    virtual void print() { cout << "Base::print" << endl; }
    void show() { cout << "Base::show" << endl; }
};

class Derived : public Base {
public:
    void print() override { cout << "Derived::print" << endl; }
    void show() { cout << "Derived::show" << endl; }
};

int main() {
    Base *b = new Derived();
    b->print();
    b->show();
    delete b;
    return 0;
}`,
    options: [
      { id: "A", text: "Base::print followed by Base::show" },
      { id: "B", text: "Derived::print followed by Base::show" },
      { id: "C", text: "Derived::print followed by Derived::show" },
      { id: "D", text: "Base::print followed by Derived::show" },
    ],
    correctAnswer: "B",
    explanation: {
      correctReason: "'print()' is declared 'virtual' in Base, so late binding occurs via the vtable; at runtime, the Derived implementation is resolved ('Derived::print'). 'show()' is NOT virtual, so the compiler uses early binding based on the pointer's declared type (Base*), invoking 'Base::show'.",
      concept: "Virtual methods trigger dynamic dispatch (vtable lookup) at runtime. Non-virtual methods are statically resolved at compile time based on the static type of the pointer.",
      takeaway: "Always check which methods have the 'virtual' keyword in inheritance hierarchies to determine whether dynamic dispatch applies.",
      wrongOptionsAnalysis: "Option C assumes show() is virtual; Option A assumes print() is statically resolved.",
    },
    tags: ["C++", "Virtual Functions", "Polymorphism", "Vtable"],
    estimatedTimeMinutes: 3,
  },
  {
    id: "capg-cpp-02",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "Constructors & Destructors",
    difficulty: "Medium",
    type: "output-prediction",
    title: "Inheritance Constructor and Destructor Execution Order",
    question: "What is the exact sequence of outputs generated by this program?",
    language: "cpp",
    codeSnippet: `#include <iostream>
using namespace std;

class Alpha {
public:
    Alpha() { cout << "1"; }
    ~Alpha() { cout << "2"; }
};

class Beta : public Alpha {
public:
    Beta() { cout << "3"; }
    ~Beta() { cout << "4"; }
};

int main() {
    Beta obj;
    return 0;
}`,
    options: [
      { id: "A", text: "1342" },
      { id: "B", text: "3124" },
      { id: "C", text: "1324" },
      { id: "D", text: "3142" },
    ],
    correctAnswer: "A",
    explanation: {
      correctReason: "When a derived object 'Beta' is created, its base class constructor executes first (prints '1'), followed by the derived class constructor (prints '3'). Upon exiting main, destruction occurs in the exact reverse order of construction: derived class destructor executes first (prints '4'), followed by base class destructor (prints '2'). Combined sequence: 1342.",
      concept: "Construction order is Base -> Derived; Destruction order is Derived -> Base (LIFO / stack order).",
      takeaway: "Remember the golden rule: Constructors build from the ground up (Base first); Destructors dismantle from top down (Derived first).",
      wrongOptionsAnalysis: "Option B reverses constructor order; Option C destroys base before derived, which is invalid.",
    },
    tags: ["C++", "Constructors", "Destructors", "Inheritance"],
    estimatedTimeMinutes: 2,
  },
  {
    id: "capg-cpp-03",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "STL Vector Iterator Invalidation",
    difficulty: "Hard",
    type: "debugging",
    title: "Vector Iterator Invalidation During Erase",
    question: "The following C++ function aims to remove all even numbers from a vector, but causes a runtime crash or undefined behavior. Identify the bug and fix.",
    language: "cpp",
    codeSnippet: `void removeEvens(vector<int>& vec) {
    for (auto it = vec.begin(); it != vec.end(); ++it) {
        if (*it % 2 == 0) {
            vec.erase(it);
        }
    }
}`,
    options: [
      { id: "A", text: "Vector cannot contain even numbers" },
      { id: "B", text: "vec.erase(it) invalidates 'it'; the loop then increments an invalid iterator and skips the adjacent element" },
      { id: "C", text: "erase() requires an integer index instead of an iterator" },
      { id: "D", text: "The loop must use reverse_iterator only" },
    ],
    correctAnswer: "B",
    explanation: {
      correctReason: "In std::vector, erase() invalidates the iterator pointing to the removed element and all subsequent iterators. Incrementing '++it' on an invalidated iterator causes undefined behavior. In addition, elements shift left, so unconditionally incrementing 'it' skips the element that moved into the erased position. Fix: 'it = vec.erase(it);' without '++it' in that branch, or use std::erase_if.",
      concept: "vec.erase(it) returns an iterator to the element immediately following the removed element. That return value must be assigned back to 'it'.",
      takeaway: "Iterator invalidation is a classic C++ systems and campus interview question.",
      wrongOptionsAnalysis: "Option A is nonsensical; Option C is incorrect (std::vector::erase takes an iterator); Option D does not solve the root invalidation issue.",
    },
    tags: ["C++", "STL", "Iterators", "Vectors", "Debugging"],
    estimatedTimeMinutes: 3,
  },
  {
    id: "capg-cpp-04",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "Static Class Members",
    difficulty: "Medium",
    type: "output-prediction",
    title: "Static Member Variable Sharing Across Instances",
    question: "What will be printed when this program runs?",
    language: "cpp",
    codeSnippet: `#include <iostream>
using namespace std;

class Counter {
public:
    static int count;
    Counter() { count++; }
};

int Counter::count = 0;

int main() {
    Counter c1;
    Counter c2;
    Counter c3;
    cout << c1.count << " " << c2.count << " " << Counter::count << endl;
    return 0;
}`,
    options: [
      { id: "A", text: "1 2 3" },
      { id: "B", text: "3 3 3" },
      { id: "C", text: "1 1 1" },
      { id: "D", text: "Compilation Error" },
    ],
    correctAnswer: "B",
    explanation: {
      correctReason: "'count' is a static class variable, meaning there is only one shared memory location for the entire class, rather than a separate copy per object. When c1, c2, and c3 are instantiated, the constructor runs 3 times, incrementing the single shared variable to 3. Accessing c1.count, c2.count, or Counter::count all refer to the exact same value 3.",
      concept: "Static data members have class scope and static storage duration. They belong to the class, not individual object instances.",
      takeaway: "In C++, accessing a static member via an instance pointer/object (c1.count) is syntactically permitted, but refers to the shared class-level member.",
      wrongOptionsAnalysis: "Option A falsely assumes each object holds a snapshot; Option D overlooks that Counter::count is properly defined outside the class.",
    },
    tags: ["C++", "Static", "OOP", "Classes"],
    estimatedTimeMinutes: 2,
  },
  {
    id: "capg-cpp-05",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "Virtual Destructors",
    difficulty: "Hard",
    type: "scenario",
    title: "Deleting Derived Object via Base Pointer Without Virtual Destructor",
    question: "Consider: 'Base *ptr = new Derived(); delete ptr;'. If Base's destructor is NOT declared virtual, what is the consequence?",
    options: [
      { id: "A", text: "Compilation error: delete requires a virtual destructor" },
      { id: "B", text: "Undefined behavior and resource leak: only Base::~Base() is called, Derived::~Derived() is never executed" },
      { id: "C", text: "The C++ runtime automatically detects the derived object and calls both destructors safely" },
      { id: "D", text: "Derived::~Derived() is called first, but Base::~Base() is skipped" },
    ],
    correctAnswer: "B",
    explanation: {
      correctReason: "If a base class destructor is non-virtual, deleting a derived class object through a pointer to base results in undefined behavior (C++ standard [expr.delete]). In practice, the compiler statically binds to Base::~Base(); the Derived destructor never runs, leaking any resources (memory, file handles, locks) owned by Derived.",
      concept: "Any class designed to be used polymorphically as a base class should declare a virtual destructor (or protected non-virtual destructor).",
      takeaway: "Whenever you write a class with virtual functions, immediately declare a virtual destructor.",
      wrongOptionsAnalysis: "Option A is wrong (the compiler emits code with a warning); Option C is incorrect as C++ does not provide automatic runtime dispatch without virtual.",
    },
    tags: ["C++", "Destructors", "Memory Leak", "Virtual"],
    estimatedTimeMinutes: 2,
  },
  {
    id: "capg-cpp-06",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "References vs Pointers",
    difficulty: "Easy",
    type: "mcq",
    title: "Core Distinctions Between References and Pointers in C++",
    question: "Which of the following statements about C++ references is TRUE?",
    options: [
      { id: "A", text: "References can be re-bound to point to another object after initialization" },
      { id: "B", text: "References can be NULL" },
      { id: "C", text: "A reference must be initialized when declared and cannot be reseated" },
      { id: "D", text: "sizeof(ref) always returns the size of a pointer (4 or 8 bytes)" },
    ],
    correctAnswer: "C",
    explanation: {
      correctReason: "In C++, a reference is an alias for an existing object. It must be bound to a valid object upon declaration ('int &r = x;') and can never be reseated to refer to another object throughout its lifetime (assigning 'r = y' assigns the value of y into x).",
      concept: "References provide safer syntax than pointers: no null references (in valid C++), no arithmetic offset manipulation, and mandatory initialization.",
      takeaway: "Remember: Pointers can be null and reseated; References cannot be null and cannot be reseated.",
      wrongOptionsAnalysis: "Option A is false (references cannot be reseated); Option B is false; Option D is false (sizeof on a reference returns sizeof the referred type).",
    },
    tags: ["C++", "References", "Pointers", "Language Rules"],
    estimatedTimeMinutes: 1,
  },
  {
    id: "capg-cpp-07",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "Dangling References",
    difficulty: "Medium",
    type: "debugging",
    title: "Returning Reference to Local Stack Variable Bug",
    question: "Identify the critical defect in the following C++ function:",
    language: "cpp",
    codeSnippet: `const string& getGreeting(const string& name) {
    string greeting = "Hello, " + name + "!";
    return greeting;
}`,
    options: [
      { id: "A", text: "Strings cannot be concatenated with the + operator in C++" },
      { id: "B", text: "Returns a reference to a local variable 'greeting' that is destroyed when the function returns" },
      { id: "C", text: "The parameter 'name' must not be const" },
      { id: "D", text: "C++ requires returning char* for greetings" },
    ],
    correctAnswer: "B",
    explanation: {
      correctReason: "'greeting' is a local stack variable allocated inside getGreeting(). When the function returns, 'greeting' is destroyed by its destructor. Returning 'const string&' gives the caller a dangling reference to deallocated memory, leading to crashes or data corruption when accessed.",
      concept: "Never return a reference or pointer to a local variable created on the function's stack frame.",
      takeaway: "Return by value: 'string getGreeting(...)'. Modern C++ uses Return Value Optimization (RVO) and move semantics, making return-by-value both safe and zero-copy.",
      wrongOptionsAnalysis: "Option A is false (std::string supports operator+); Option C and D are false.",
    },
    tags: ["C++", "Dangling Reference", "Memory", "Debugging"],
    estimatedTimeMinutes: 2,
  },
  {
    id: "capg-cpp-08",
    category: "cpp",
    categoryLabel: "C / C++",
    topic: "Operator Overloading & Copy Assignment",
    difficulty: "Hard",
    type: "mcq",
    title: "Self-Assignment Guard in Operator=",
    question: "Why should a custom copy assignment operator 'MyClass& operator=(const MyClass& rhs)' always check 'if (this == &rhs)' before copying resources?",
    options: [
      { id: "A", text: "To prevent infinite recursion during assignment" },
      { id: "B", text: "To prevent deleting its own existing dynamic resources before copying when self-assigned (e.g., obj = obj;)" },
      { id: "C", text: "C++ syntax requires the 'this' comparison to compile" },
      { id: "D", text: "To verify that both objects have the exact same virtual table" },
    ],
    correctAnswer: "B",
    explanation: {
      correctReason: "If an object assigns to itself (e.g. *p = *q where p and q point to the same object) without a self-assignment guard, releasing the existing dynamic memory (e.g., 'delete[] buffer;') inadvertently destroys the source data before the copy occurs, resulting in undefined behavior or crash.",
      concept: "The Rule of Three/Five requires safe handling of self-assignment, often achieved with 'if (this == &rhs) return *this;' or the copy-and-swap idiom.",
      takeaway: "In custom resource management classes, self-assignment safety is a standard interview discussion topic.",
      wrongOptionsAnalysis: "Option A is false; Option C is false (it compiles without it); Option D is unrelated.",
    },
    tags: ["C++", "Operator Overloading", "Assignment", "Memory Management"],
    estimatedTimeMinutes: 2,
  },
];
